#!/bin/bash

# Switches
LIGHT_SW=29
WATER_SW=

# Sensors
WATER_RD=
TEMP_RD=
MOIST_RD=

set -e

if ! which gpio >/dev/null 2>&1; then
    echo "gpio program missing."
    echo "Please install from http://wiringpi.com."
    exit 1
fi

cd /opt/greenhouse
. functions

command="$1"
shift
echo gh_"$command" "$@"

exit "$?"

