#!/bin/bash

# Switches
LIGHT_SW=29
WATER_SW=

# Sensors
WATER_RD=
TEMP_RD=
MOIST_RD=

set -e

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

if ! which gpio >/dev/null 2>&1; then
    echo "gpio program missing."
    echo "Please install from http://wiringpi.com."
    exit 1
fi

cd /opt/greenhouse
. functions

command="$1"
shift
gh_"$command" "$@"

exit "$?"

