#!/bin/bash

# Switches
LIGHT_SW=29
WATER_SW=

# Sensors
WATER_RD=
TEMP_RD=
MOIST_RD=

set -e

if ! which gpio >/dev/null 2>&1; then
    echo "gpio program missing."
    echo "Please install from http://wiringpi.com."
    exit 1
fi

cd /opt/greenhouse


function lights {
    case "$0" in
	on )
	    gpio mode "$LIGHT_SW" out
	    gpio write "$LIGHT_SW" 1
	    ;;
	off )
	    gpio mode "$LIGHT_SW" out
	    gpio write "$LIGHT_SW" 0
	    ;;
	read )
	    gpio mode "$LIGHT_SW" in
	    gpio read "$LIGHT_SW"
	    ;;
	* )
	    echo "Error"
	    exit 1
	    ;;
    esac
}
